export const cryptoCoinIds = {
    BTC: "bitcoin",
    ETH: "ethereum",
    AVAX: "avalanche-2",
    SOL: "solana",
    SUI: "sui",
    GRAM: "the-open-network",
    AR: "arweave",
    S: "sonic-3",
    XRP: "ripple",
    DOT: "polkadot",
    LINK: "chainlink",
    ADA: "cardano",
    BNB: "binancecoin",
    XLM: "stellar",
    HYPE: "hyperliquid",
    BCH: "bitcoin-cash",
    CC: "canton-network",
};